version: '3'
services:
  postgres-service:
    image: postgres:9.6
    volumes:
      - pddata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: d3hard
      POSTGRES_USER: d3hard
      POSTGRES_PASSWORD: d3hard
  d3hard:
    image: d3hard
    ports:
    - 9000:9000
    environment:
      DB_USER: d3hard
      DB_PASSWORD: H5pAuqmpB8XGTeeAgs
      DB_URL: jdbc:postgresql://postgres-service:5432/d3hard
      D3_CLIENT_ID: YOUR_CLIENT_ID
      D3_CLIENT_SECRET: YOUR_CLIENT_SECRET
  d3web:
    image: d3web
    ports:
      - 80:80
    extra_hosts:
      - "d3env-d3hard:172.17.0.1"

volumes:
  mysqldb:




