version: '3'
services:
  mysql-service:
    image: mysql:5.7.24
    volumes:
    - mysqldb:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: TAeKOHIWzoAHdAmacB
      MYSQL_DATABASE: d3hard
      MYSQL_USER: d3hard
      MYSQL_PASSWORD: H5pAuqmpB8XGTeeAgs
    ports:
    - "3306:3306"
  web-admin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: TAeKOHIWzoAHdAmacB
      MYSQL_USER: d3hard
      MYSQL_PASSWORD: H5pAuqmpB8XGTeeAgs
      PMA_HOST: mysql-service
    ports:
    - "22080:80"
  d3hard:
    image: d3hard
    ports:
    - 9000:9000
    environment:
      D3_CLIENT_ID: YOUR_DIABLO_API_CLIENT_ID
      D3_CLIENT_SECRET: YOUR_DIABLO_API_SECRET
      DB_USER: d3hard
      DB_PASSWORD: H5pAuqmpB8XGTeeAgs
      DB_URL: jdbc:mysql://mysql-service:3306/d3hard?useSSL=false
volumes:
  mysqldb:




