version: 0.0.1

# Change default server ports
server:
  rootPath: /api/
  applicationConnectors:
    - type: http
      port: 9000

  adminConnectors:
    - type: http
      port: 9001

blizard:
  clientId: ${D3_CLIENT_ID:-CLIENT_ID_VALUE}                  # use D3_CLIENT_ID ENV OR VALUE (- not part of VALUE)
  clientSecret:  ${D3_CLIENT_SECRET:-CLIENT_SECRET}           # use D3_CLIENT_SECRET ENV OR VALUE (- not part of VALUE)

database:
  driverClass: com.mysql.cj.jdbc.Driver   
  user: ${DB_USER:-d3hard}                                     # use DB_USER ENV OR VALUE (- not part of VALUE)
  password: ${DB_PASSWORD:-d3hard}                             # use DB_PASSWORD ENV OR VALUE (- not part of VALUE)
  url: ${DB_URL:-jdbc:mysql://mysql-service:3306/d3hard?useSSL=false}
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.hbm2ddl.auto: update

  validationQuery: "SELECT now()"
  # the minimum number of connections to keep open
  minSize: 4
  initialSize: 4

  # the maximum number of connections to keep open
  maxSize: 8

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

logging:
  loggers:
    "org.hibernate.engine.internal.StatisticalLoggingSessionEventListener":
      level: OFF
    "com.kldev.d3.storage.dao":
      level: ${D3_LOG_LEVEL:-ERROR}            # ERROR / INFO