version: 0.0.1

# Change default server ports
server:
  rootPath: /api/
  applicationConnectors:
    - type: http
      port: 9000

  adminConnectors:
    - type: http
      port: 9001

blizard:
  clientId: ${D3_CLIENT_ID:-CLIENT_ID_VALUE}                  # use D3_CLIENT_ID ENV OR VALUE (- not part of VALUE)
  clientSecret:  ${D3_CLIENT_SECRET:-CLIENT_SECRET}           # use D3_CLIENT_SECRET ENV OR VALUE (- not part of VALUE)

database:
  driverClass: org.postgresql.Driver
  user: ${DB_USER:-d3hard}
  password: ${DB_PASSWORD:-d3hard}
  url: ${DB_URL:-jdbc:postgresql://postgres-service:5432/d3hard}
  properties:
    charSet: UTF-8
    hibernate.dialect:  org.hibernate.dialect.PostgreSQL95Dialect
    hibernate.hbm2ddl.auto: update

  validationQuery: "SELECT now()"

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

logging:
  loggers:
    "org.hibernate.engine.internal.StatisticalLoggingSessionEventListener":
      level: OFF
    "com.kldev.d3.storage.dao":
      level: ${D3_LOG_LEVEL:-ERROR}            # ERROR / INFO