version: '3'
services:
  postgres-service:
    image: postgres:9.6
    volumes:
    - pddata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: d3hard
      POSTGRES_USER: d3hard
      POSTGRES_PASSWORD: d3hard
    ports:
    - "5432:5432"
volumes:
  pddata:


